# Generated by Django 3.2.4 on 2021-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('IsMarried', models.BooleanField(default=False)),
                ('Occupation', models.CharField(max_length=100)),
                ('Income', models.CharField(max_length=100)),
            ],
        ),
    ]
