# Generated by Django 3.2.4 on 2021-07-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
